name: jupyter_dashboards_workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - python>3.7
  - notebook>5.2
  - jupyter_dashboards
  - jupyter_dashboards_bundlers
  - numpy
  - math
  - pandas
  - seaborn
  - matplotlib
  - sympy
